name: Build-sphinx-docs

on:
  push:
    branches:
      - main
  pull_request:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: "${{ env.X86_64_PYTHON_VERSION }}"

      - name: Install dependencies
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # pandoc is needed to load jupyter notebooks in html
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
      # Graphviz is needed for drawing graphs in documentation
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Build HTML
        working-directory: docs
        run: |
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
